server:
  port: 9524
spring:
  application:
    name: simon-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
         #uri: http://localhost:8001
         uri: lb://cloud-payment-service
         predicates:
         - Path=/payment/get/** # 断言，路径相匹配的进行路由
       - id: payment_route2
         #uri: http://localhost:8001
         uri: lb://cloud-payment-service
         predicates:
         - Path=/payment/lb/** #断言,路径相匹配的进行路由
            #- After=2020-03-12T15:44:15.064+08:00[Asia/Shanghai]
            #- Cookie=username,eiletxie   #带Cookie，并且username的值为eiletxie
            #- Header=X-Request-Id,\d+ #请求头要有 X-Request-Id属性并且值为整数的正则表达式

eureka:
  instance:
    hostname: simon-cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
